export enum DMRequestStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  CANCELED = 'CANCELED',
  AWAITING_COMPLETION = 'AWAITING_COMPLETION',
  COMPLETED = 'COMPLETED',
}