export enum NotificationType {
  // Interaction Notifications
  POST_LIKED = 'POST_LIKED',
  POST_COMMENTED = 'POST_COMMENTED',
  POST_SHARED = 'POST_SHARED',
  POST_FAVORITED = 'POST_FAVORITED',
  COMMENT_LIKED = 'COMMENT_LIKED',
  COMMENT_REPLIED = 'COMMENT_REPLIED',

  // Trust & Follow Notifications
  NEW_TRUSTER = 'NEW_TRUSTER',
  NEW_TRUSTED_BY = 'NEW_TRUSTED_BY',

  // Messaging Notifications
  NEW_MESSAGE = 'NEW_MESSAGE',
  DM_REQUEST_RECEIVED = 'DM_REQUEST_RECEIVED',
  DM_REQUEST_ACCEPTED = 'DM_REQUEST_ACCEPTED',
  DM_REQUEST_DECLINED = 'DM_REQUEST_DECLINED',
  SUPPORT_REQUEST_ACCEPTED = 'SUPPORT_REQUEST_ACCEPTED',

  // Collection Notifications
  COLLECTION_POST_ADDED = 'COLLECTION_POST_ADDED',
  COLLECTION_SHARED = 'COLLECTION_SHARED',

  // Gamification Notifications
  NEW_BADGE = 'NEW_BADGE',
  ACHIEVEMENT_UNLOCKED = 'ACHIEVEMENT_UNLOCKED',
  LEVEL_UP = 'LEVEL_UP',
  REWARD_EARNED = 'REWARD_EARNED',

  // Expert Notifications
  EXPERT_REQUEST_AVAILABLE = 'EXPERT_REQUEST_AVAILABLE',
  EXPERT_REQUEST_ANSWERED = 'EXPERT_REQUEST_ANSWERED',

  // Event Notifications
  EVENT_STARTED = 'EVENT_STARTED',
  EVENT_ENDING_SOON = 'EVENT_ENDING_SOON',
  EVENT_REWARD_AVAILABLE = 'EVENT_REWARD_AVAILABLE',

  // System Notifications
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  ACCOUNT_SECURITY = 'ACCOUNT_SECURITY',
  TIPS_RECEIVED = 'TIPS_RECEIVED',
  TIPS_SENT = 'TIPS_SENT',

  // Wallet & Transaction Notifications
  WALLET_CONNECTED = 'WALLET_CONNECTED',
  WALLET_DISCONNECTED = 'WALLET_DISCONNECTED',
  TRANSACTION_CONFIRMED = 'TRANSACTION_CONFIRMED',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  TRANSACTION_PENDING = 'TRANSACTION_PENDING',

  // Reward Notifications
  REWARD_CLAIMABLE = 'REWARD_CLAIMABLE',
  REWARD_CLAIMED = 'REWARD_CLAIMED',
  REWARD_EXPIRED = 'REWARD_EXPIRED',
  MULTIPLE_REWARDS_AVAILABLE = 'MULTIPLE_REWARDS_AVAILABLE',

  // NFT Notifications
  NFT_RECEIVED = 'NFT_RECEIVED',
  NFT_SENT = 'NFT_SENT',
  NFT_SOLD = 'NFT_SOLD',
  NFT_PURCHASED = 'NFT_PURCHASED',
  NFT_LISTED = 'NFT_LISTED',
  NFT_LISTING_SOLD = 'NFT_LISTING_SOLD',
}

