export enum RewardSourceType {
  LADDER_REWARD = 'LADDER_REWARD',
  TIPS_RECEIVED = 'TIPS_RECEIVED',
  SUPPORT_SESSION = 'SUPPORT_SESSION',
  BADGE_EARNED = 'BADGE_EARNED',
  ACHIEVEMENT_UNLOCKED = 'ACHIEVEMENT_UNLOCKED',
  EVENT_PARTICIPATION = 'EVENT_PARTICIPATION',
  SYSTEM_GRANT = 'SYSTEM_GRANT',
}
