  # Test ortamı için Elastic Beanstalk deploy workflow'u
  # Bu workflow, 'test' branch'ine push olduğunda tetiklenir ve AWS Elastic Beanstalk'a deploy eder.
  # Test ortamı için Elastic Beanstalk deploy workflow'u
  # Bu workflow, 'test' branch'ine push olduğunda tetiklenir ve AWS Elastic Beanstalk'a deploy eder.

  name: Deploy to AWS Elastic Beanstalk (Prod)

  on:
    push:
      branches:
        - prod
  jobs:
    deploy:
      name: Deploy to Elastic Beanstalk Prod
      runs-on: ubuntu-latest
      environment: prod
      steps:
        # 1. Repo'yu checkout et
        - name: Checkout repository
          uses: actions/checkout@v4

        # 2. Node.js'i kur
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
        # 2. Node.js'i kur
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'

        # 3. Bağımlılıkları yükle
        - name: Install dependencies
          run: npm ci
        # 3. Bağımlılıkları yükle
        - name: Install dependencies
          run: npm ci

        # 3.5. Prisma Client'ı generate et
        - name: Generate Prisma Client
          run: npx prisma generate
        # 3.5. Prisma Client'ı generate et
        - name: Generate Prisma Client
          run: npx prisma generate

        # 4. Projeyi build et
        - name: Build project
          run: npm run build
        # 4. Projeyi build et
        - name: Build project
          run: npm run build

        # 5. Projeyi zip'le (sadece gerekli dosyalar)
        - name: Zip project files
          run: |
            zip -r deploy.zip dist node_modules package.json package-lock.json .env.production
        # 5. Projeyi zip'le (sadece gerekli dosyalar)
        - name: Zip project files
          run: |
            zip -r deploy.zip dist node_modules package.json package-lock.json .env.production

        # 6. Elastic Beanstalk'a deploy et
        - name: Deploy to Elastic Beanstalk
          uses: einaregilsson/beanstalk-deploy@v21
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_TEST }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST }}
            application_name: tipbox-backend-prod
            environment_name: app-backend-prod-env
            region: eu-central-1
            version_label: ${{ github.sha }}
            deployment_package: deploy.zip
            use_existing_version_if_available: true